### ISSUE TITLE
Unable to compile crate with dash in name

### ISSUE THREAD

**Issue by faern** [iqlusioninc/abscissa#100]
If I try to create an Abscissa crate that has a dash in the name, then it will create invalid code. Since in the code the crate name has to replace dashes with underscores.

How to reproduce:
```bash
$ abscissa new abscissa-test
...

$ cd abscissa-test/

$ cargo build
   Compiling abscissa-test v0.1.0 (/home/user/src/abscissa-test)
error: expected one of `::`, `;`, or `as`, found `-`
 --> src/bin/abscissa-test/main.rs:6:13
  |
6 | use abscissa-test::application::APPLICATION;
  |             ^ expected one of `::`, `;`, or `as` here
```

**Comment by tarcieri** [comment]
The framework conventions are mostly around `_` in the name, but that said I would consider this a bug and it should probably replace all `-` with `_` before doing the rest of the conversions (ala crate names)
