### ISSUE TITLE
crates: Consider `err-derive`

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/abscissa#103]
Presently Abscissa uses the [`failure`](https://crates.io/crates/failure) as its error handling abstraction, and uses the following features:

- `failure_derive` proc macro "DSL" for describing errors
- `cause` support for capturing error causes (and potentially downcasting them)
- `backtrace` support

In the intervening time since we selected failure `std::error:Error` got a new [Error::source](https://doc.rust-lang.org/beta/std/error/trait.Error.html#method.source) method which supports downcasting.

My understanding is there's also some work underway to consume the `backtrace` crate as part of `std`, however I can't find references to it. That said, Abscissa uses a generic [`abscissa_core::error::Error<Kind>`](https://docs.rs/abscissa_core/latest/abscissa_core/error/struct.Error.html) type, so capturing and storing backtraces directly is potentially doable.

That leaves the error-handling DSL as the main compelling reason to continue using `failure`. The [`err-derive`](https://users.rust-lang.org/t/announcing-err-derive-yet-another-error-handling-library/23594) crate seems like a popular new alternative to `failure_derive`.

I think `failure` had good goals when it started, like unifying error handling for `std` and `no_std` programs, and addressing shortcomings of `std::error::Error` in a third party crate. But because Abscissa is very much `std` dependent, and because `std::error::Error` has improved, `failure` is less compelling, and the schism between `std::error::Error` and `failure::Fail` is somewhat problematic.

I think the main compelling reason to switch would be if `std::error::Error` ever gets first-class backtrace support, but it's something we can also consider doing earlier.

It appears `err-derive` adds one additional transitive compile time dependency (`rustc_version`) but otherwise has the same dependencies as `failure`.

**Comment by tarcieri** [comment]
Closing in favor of #144
