### ISSUE TITLE
Incorrect description of the crate name in the FAQ

### ISSUE THREAD

**Issue by franky47** [iqlusioninc/abscissa#104]
The Readme states:
> Q1: Why is it called "abscissa"?
> 
> A1: An abscissa represents the elevation of a point above the x-axis. In that regard, "Abscissa" can be thought of as a pun about getting off the ground, or elevating your project.

This is incorrect: the abscissa corresponds to the X coordinate in a Cartesian system, and represents the horizontal distance of a point to the origin, not the vertical one (or elevation as mentioned, which is represented by the ordinate).
https://en.wikipedia.org/wiki/Abscissa_and_ordinate

The name is a good one nonetheless, but for the sake of mathematical correctness and general credibility, this FAQ entry should probably be rephrased.

**Comment by tarcieri** [comment]
Le sigh, and this after someone told me the opposite #102
