### ISSUE TITLE
Usage information is illegible on light backgrounds

### ISSUE THREAD

**Issue by csterritt** [iqlusioninc/abscissa#105]
Hi -- Not all of us use dark themes, and so I got to see this on startup of a base abscissa app:

<img width="446" alt="Screen Shot 2019-07-25 at 6 23 44 PM" src="https://user-images.githubusercontent.com/37917/61912974-a471d200-af09-11e9-9f6e-6066b43ba495.png">

The white text on the light background is not wonderful :-(

I don't think there's any "magic" color which looks good everywhere, so perhaps just don't use colors at all by default?  In other words, please respect the color choices I've made for my terminal.

Thanks!

**Comment by tarcieri** [comment]
You can disable colors in your application by defining the `Application::term_colors` method however you like:

https://docs.rs/abscissa_core/0.2.0/abscissa_core/application/trait.Application.html#method.term_colors

```
    fn term_colors(&self, command: &Self::Cmd) -> ColorChoice {
        ColorChoice::None
    }
```

As for disabling colors by default in the template, I'd rather not. The white is bad but the rest looks fine to me. I can look into some alternative for the white that look ok on a light background too.

It might also be possible to have color palettes for light and dark backgrounds. It seems like there might also be [some options for detecting the background color](https://gist.github.com/blueyed/c8470c2aad3381c33ea3).

I'm going to leave this issue open, however I hope you don't mind if I change the title to be a little more general.

**Comment by ErichDonGubler** [comment]
Why are neutral colors even used at all in here? Normally, the solution would be to just use the "default" color everywhere, you need something legible. Having contrast between elements is good -- however, this is normally done with font weight (i.e., bold, weak) precisely so that one doesn't have to worry about foreground color.

**Comment by tarcieri** [comment]
@ErichDonGubler that's something we can experiment with
