### ISSUE TITLE
Component registry never registers components - component registry doesn't work.

### ISSUE THREAD

**Issue by lberezy** [iqlusioninc/abscissa#111]
https://github.com/iqlusioninc/abscissa/blob/710e10618d75b3aaa796ad5f5f96c9531fc0171c/core/src/component/registry.rs#L35

It seems that the register function goes through all the motions of registering a new set of components, but never actually mutates the registry to insert them.
Is this a known issue, not implemented yet, or am I using the registry wrong?

This breaks the ability to use registered components in applications.
In generated `application.rs` for example:
```rust
/// Register all components used by this application.
///
/// If you would like to add additional components to your application
/// beyond the default ones provided by the framework, this is the place
/// to do so.
fn register_components(&mut self, command: &Self::Cmd) -> Result<(), FrameworkError> {
    let mut components = self.framework_components(command)?;
    // expect the application's components register to contain:
    // abscissa_core::terminal
    // abscissa_core::logging
    self.state.components.register(components)?;

    // No components are found :(
    for component in self.state.components.iter() {
        println!("registered component: {}", component.name())
    }
    Ok(())
}
```

**Comment by tarcieri** [comment]
@lberezy short answer: components need a big overhaul.

Our use of components right now is entirely for "initializers", which initialize state stored elsewhere, and none of them are stateful, so it's almost certainly a bug if you're trying to do stateful components. In as much as we're using the registry, it's to sort the components in the proper initialization order.

I'd like to switch components to use some sort of index allocator (or generational index allocator, possibly [generational-arena](https://github.com/fitzgen/generational-arena)), which would allow them to refer to each other by handles to their (generational) index.

**Comment by lberezy** [comment]
Damn, that's a little sad to hear but I understand where you're coming from.

Any chance that a basic implementation might happen (even if the performance is poor), just so people can use the components system (it's the second advertised dotpoint in `README.md`) productively?

**Comment by lberezy** [comment]
Looks like there are still some issues in the Registry, namely I can't seem to get

**Comment by tarcieri** [comment]
@lberezy thanks for #112. I'm going to do a pass on the component registry and convert it to a `generational-arena`, as well as adding tests as clearly this is horked in any number of ways.

I would not be surprised if you can't practically use the `TypeId`-based lookup yet.

I think what's needed is to build indexes from the registered name to the handles in the `generational-arena`. I can try the `TypeId` approach but we may just need to look them up by name and use the type parameter for the downcast only.

**Comment by tarcieri** [comment]
This PR contains a fairly big overhaul of the component system which better follows ECS concepts around components:

https://github.com/iqlusioninc/abscissa/pull/113

**Comment by lberezy** [comment]
Woah that's looking pretty good and done so fast, I definitely like the concept of using a generational arena! Hopefully I've have some time in the coming days to have a good look at it and use it.

Thanks

**Comment by tarcieri** [comment]
This PR adds a basic set of component tests:

https://github.com/iqlusioninc/abscissa/pull/116

I will add back the (previously broken) downcasting functionality in a follow-up PR (with tests), now that I think I understand how to implement it correctly.

**Comment by tarcieri** [comment]
This PR adds back downcasting functionality, now with tests:

https://github.com/iqlusioninc/abscissa/pull/117/files

It requires a few weird tricks to make work (namely an `AsAny` helper trait with a blanket impl and a double deref on the `Box` types), but the tests confirm it's now working.

I'm going to follow up by trying to index components by their `TypeId` for faster lookup.

**Comment by tarcieri** [comment]
#118 indexes the registry by `TypeId`.

I still plan on adding custom derive support for `Component`, but I'd say these changes should address the original concerns in this issue.

Please reopen if you disagree.
