### ISSUE TITLE
Allow finer grained control over argument parsing style and error display

### ISSUE THREAD

**Issue by jarrodldavis** [iqlusioninc/abscissa#120]
Currently, `abscissa_core` delegates to `gumdrop`'s parsing logic with its default parsing style and error formatting:

https://github.com/iqlusioninc/abscissa/blob/67097d53dfa45607448b314b9dbd55752d4249ba/core/src/command.rs#L32-L39

It would be nice if the following were possible:

- override the `ParsingStyle` to use `StopAtFirstFree` using `Options::parse_args`
- customize the error output when option parsing fails – the current behavior bypasses the generated application's error formatting in `src/errors.rs`:
https://github.com/iqlusioninc/abscissa/blob/67097d53dfa45607448b314b9dbd55752d4249ba/cli/template/src/error.rs.hbs#L23-L27

**Comment by tarcieri** [comment]
@jarrodldavis will consider these. Thanks for opening the issue.

**Comment by tony-iqlusion** [comment]
Closed by #562 (clap v3 migration)
