### ISSUE TITLE
Open up wiki ? 

### ISSUE THREAD

**Issue by tjyang** [iqlusioninc/abscissa#138]
Hi 
I like to become a abscissa user(not developing abscissa itself).
I will document abscissa from end user perspective. 
Would you consider enable wiki to take in notes/docs  from users ?

**Comment by tarcieri** [comment]
My plan for documentation was to create an in-repo Gitbook. I’m not really a fan of open wikis: in addition to general spam, they bypass a code review process, and in doing so tend to accumulate inaccuracies.

The other nice thing about keeping the docs in-repo is they facilitate atomic changes between code and documentation.

**Comment by tjyang** [comment]
Thanks for response, I will be  taking my own notes at https://github.com/learnrust/abscissa/wiki/Running-abscissa-on-Fedora for now.
