### ISSUE TITLE
Need help writing tests

### ISSUE THREAD

**Issue by WyseNynja** [iqlusioninc/abscissa#145]
I have lots of logging in my application code which is helpful when doing `cargo run`, but `cargo test` doesn't have any initialization for config or logging.

Right now, I use `println!` in my test code, but I'd like to see some of the debug logs from the application code, too.

I also want to test some functions that have calls to `app_config()`, but right now they fail with an error about config not being initialized.

How should I setup config and logging without running `boot` in my tests?

**Comment by tarcieri** [comment]
There's presently no way to do this other than booting the application. Configuration is stored in the application singleton, deliberately behind an `RwLock` in order to support hot configuration reloads in a manner that ensures the thread mutating the configuration has exclusive access to all application state (with the intent of eventually supporting things like reloading components).

**Comment by WyseNynja** [comment]
Thanks.

For logging, I think I'll do something like https://github.com/psFried/test-logger (but with updated deps).

Is there any way to boot the application and then run arbitrary code?

**Comment by tarcieri** [comment]
You can use `Application::init` on a (`Default::default()`) instance of your application to initialize it. Here's where that happens in the normal application lifecycle:

https://github.com/iqlusioninc/abscissa/blob/develop/core/src/application.rs#L56

Note that for `app_config()` to work, you'll need to set the application single value to this instance after it's booted (see the subsequent lines in the above function for how that works).

**Comment by WyseNynja** [comment]
So I got this partly working. However, the logs escape the output capturing of `cargo test`.

env_logger has a `is_test` method that works like I need. Perhaps something like that could be added to abscissa's logging? https://docs.rs/env_logger/0.6.1/env_logger/#capturing-logs-in-tests

Here's what I have so far. I'm sure it could be improved.

```
#[cfg(test)]
pub mod tests {
    use abscissa_core::application::Application;
    use abscissa_core::command::Command;
    use abscissa_core::EntryPoint;
    use lazy_static::lazy_static;
    use parking_lot::Mutex;

    use crate::application::DexDashboardApp;
    use crate::commands::DexDashboardCmd;

    lazy_static! {
        // TODO: do we need an Arc around this?
        static ref APP_MUTEX: Mutex<bool> = Mutex::new(false);
    }

    /// https://medium.com/@ericdreichert/test-setup-and-teardown-in-rust-without-a-framework-ba32d97aa5ab
    pub fn with_app<T>(test: T)
        where T: FnOnce() -> () + std::panic::UnwindSafe
    {
        // because the app is in a lazy_static and the tests might alter it, it is only safe to run one test a time
        let mut lock = APP_MUTEX.lock();

        if !*lock {
            let args = vec!["start".to_string()];

            let mut app = DexDashboardApp::default();

            let command = EntryPoint::<DexDashboardCmd>::from_args(args);

            app.init(&command).unwrap();

            crate::application::APPLICATION.set(app);

            *lock = true;
        }

        // run the test
        let result = std::panic::catch_unwind(|| {
            test()
        });

        // we don't know what the test might have changed on the APPLICATION
        // TODO: restore config to what we started with before the tests

        drop(lock);

        result.expect("test failed");
    }
}
```

Then my tests that need the app or logging looks like this:
```
#[test]
fn test_something() {
    crate::tests::with_app(|| {
        ...
    })
}
```

**Comment by tarcieri** [comment]
For what it's worth, we're planning on replacing Abscissa's logging backend with [`tracing`](https://crates.io/crates/tracing). I agree this is a good thing to solve, but I don't want to look into it too much until we've done that.

**Comment by WyseNynja** [comment]
Okay. `tracing` does look neat.

Until then, how can I disable the logging component? I thought changing my Cargo.toml like this would do it, but the logger is still being setup:

```
abscissa_core = { version = "0.4.0", default-features = false, features = ["config", "options", "terminal", "generational-arena", "signals", "secrets", "testing", "time"] }
```

**Comment by WyseNynja** [comment]
Looking into how the features and application are laid out, it doesn't look like I can skip the logging feature. Any suggestions?

**Comment by tarcieri** [comment]
Logging is one of the default framework components:

https://github.com/iqlusioninc/abscissa/blob/develop/core/src/application.rs#L121

You can swap it out in the `register_components` method of your `Application`:

https://github.com/iqlusioninc/abscissa/blob/develop/cli/template/src/application.rs.hbs#L87
