### ISSUE TITLE
RUST_LOG support.

### ISSUE THREAD

**Issue by hdevalence** [iqlusioninc/abscissa#228]
Per https://github.com/iqlusioninc/abscissa/pull/154#issuecomment-559244285, `RUST_LOG` support for `tracing` was left unresolved. It'd be nice to have it for, e.g., https://github.com/ZcashFoundation/zebra/issues/98 (cc @dconnolly)

One design question I'm not sure of: what should be the priority order of `RUST_LOG` and a config setting? Should `RUST_LOG` be overridden by a config option or vice versa? If `RUST_LOG` is overridden by a config option, does the presence of a config default prevent `RUST_LOG` from ever being used?

**Comment by tarcieri** [comment]
Personally I think `RUST_LOG` should override the config, but I'd be curious to look at some other ecosystem examples of how that's handled.

In general, having `RUST_LOG` working would be great!

**Comment by hdevalence** [comment]
For whatever it's worth (very little), it seems slightly easier to implement the other behavior: https://github.com/iqlusioninc/abscissa/pull/154#issuecomment-559243884

**Comment by tarcieri** [comment]
Ok, maybe start with what's easy to implement, and we can revisit it if it turns out to be an issue

**Comment by yaahc** [comment]
I think cargo generally prioritizes env variables over configs so I agree with `RUST_LOG` taking top priority
