### ISSUE TITLE
Tokio usage: abscissa_tokio::run... take_runtime() stuck in app.write()

### ISSUE THREAD

**Issue by JRAndreassen** [iqlusioninc/abscissa#246]
I have a Tokio usage question, it may be my understanding of your sequence of events , 
but I have not been able to determine it from the docs...

I have a set of sub-modules / commands that are dependent upon Tokio runtime.
They get called to perform a specific sub-task then return.
According to the doc's, Include abscissa_tokio and call run..
I added:
        components.push(Box::new(TokioComponent::new()?));
then call 
```rust
impl Runnable for XXXCmd {
    fn run(&self) {
        let config = app_config();
        let _ = abscissa_tokio::run(&APPLICATION, 
            async{ 
println!("Started {}", "Junk");
            }
        );
```
Whcih calls tokio::block_on...
Which is essentially what tokio::main does.
So, the runtime is initialized, I see all the threads in the debugger, but the 
app is stuck at (partial stack) 
  app.write
TokioComponent::take_runtime
TokioComponent::run
Waiting for the write lock...

In my case, I have no other component's / services running.
So I just need Tokio runtime initialized and available, the terminate after the run is done.

What am I missing...

Any insight would be greatly appreciated...

**Comment by JRAndreassen** [comment]
It appear's the call to "let config = app_config();"
issues the lock.
I guess the question is how do we release the lock ?

**Comment by tony-iqlusion** [comment]
The locks use RAII patterns, so you either need to acquire it within a scope i.e. `{ let config = app_config(); ... }`, or split the parts that access the config out into separate functions

**Comment by JRAndreassen** [comment]
Ahhh... cool

**Comment by tony-iqlusion** [comment]
I think we need a better solution for this in general (e.g. debug info when the application lock can't be acquired, and possibly a timeout), but otherwise this does not appear to be a framework issue, so I'm closing.
