### ISSUE TITLE
Synchronization primitives in Async

### ISSUE THREAD

**Issue by zmanian** [iqlusioninc/abscissa#271]
Absissca makes synchronization primitives for asynchronous multithreaded application contexts available. https://github.com/iqlusioninc/abscissa/blob/develop/core/src/application/lock.rs#L10-L46

Should there abscissa tokio make the async flavor of those primitives available?

Add in the equivalent of application lock with https://docs.rs/tokio/0.2.21/tokio/sync/struct.RwLock.html

**Comment by tony-iqlusion** [comment]
It's certainly possible. The only parts of Abscissa that depend on `std::sync` now are `application::lock::Reader` and `application::lock::Writer`:

https://github.com/iqlusioninc/abscissa/blob/develop/core/src/application/lock/reader.rs
https://github.com/iqlusioninc/abscissa/blob/develop/core/src/application/lock/writer.rs

Those could be made generic around a guard type which impls `Deref` and `DerefMut` respectively.

More generally it'd probably be nice to have some tweaks to the overall application template for making a Tokio app, which could wire up the concrete types to use for `std::sync` vs `tokio::sync`, and also wire up `abscissa_tokio` to launch the app.

**Comment by tony-iqlusion** [comment]
Migrated to `arc-swap` in #425
