### ISSUE TITLE
If flags and params are too long, description is missing from help output

### ISSUE THREAD

**Issue by AloeareV** [iqlusioninc/abscissa#389]
When `Options` is derived, the `usage()` output will have an extra `\n` after `long_param` if `  -short, --long long_param` is longer than 29 characters. This causes `long_param` to be set to `None`,  `description` to be set to what should be `long_param`, and the actual `help` description from that flag to be missing from the help output entirely. 

Using `lines()` here doesn't work: https://github.com/iqlusioninc/abscissa/blob/bee6525a77c36d9ed4c4bfc40919e1e72d44e7cf/core/src/command/usage.rs#L350

**Comment by tony-iqlusion** [comment]
The longer-term solution to these is an eventual migration to clapv3. See #330 

For the interim issues like this are unlikely to be solved unless you'd like to submit a PR.

**Comment by tony-iqlusion** [comment]
Closed by #562 (clap v3 migration)
