### ISSUE TITLE
How to configure a Tokio component?

### ISSUE THREAD

**Issue by nickray** [iqlusioninc/abscissa#686]
If I understand correctly, the order of events from a component perspective are:
- constructor call (in register components, no config available)
- init_tokio call (no config available, attempts to read from `APP` crash with `Message:  Abscissa application state accessed before it has been initialized!`)
- after_config call (config available, but component already running)

So if init_tokio spawns a task, how is it supposed to be configured?
Going further, why isn't the config already available in the constructor call?

**Comment by tony-iqlusion** [comment]
The intended usage for spawning a task which can access the configuration is to do inside an `abscissa_tokio::run` block, ala:

```rust
abscissa_tokio::run(&APP, async { ... })
```

This should be called from one of the `Command`s in your application, which will ensure it occurs after configuration is loaded.

There are definitely some gaps around components and configuration, and more generally with the entire current component system. That's something we'll probably try to overhaul in the next version, potentially turning configuration into a component which can be injected as an init parameter to other components when the application starts.

**Comment by nickray** [comment]
Got it. Yeah it would be good if components were configurable :)
