### ISSUE TITLE
`EntryPoint` and config paths

### ISSUE THREAD

**Issue by hdevalence** [iqlusioninc/abscissa#79]
I ran into a problem trying to load a config from a file in the following way: I implemented the `config_path` function in `impl Configurable<FooConfig> for FooCommand` to supply the correct config path, and expected the application initialization to call it in order to load the config file.  However, the default boilerplate generates an
```
impl Application for FooApplication {
    type Cmd = EntryPoint<FooCommand>;
```
so that the `command` object created here https://github.com/iqlusioninc/abscissa/blob/977b548286266923a9a1a34c17355870d12b0605/src/application.rs#L54 has type `command: EntryPoint<FooCommand>`, and so when it's configured here https://github.com/iqlusioninc/abscissa/blob/977b548286266923a9a1a34c17355870d12b0605/src/application.rs#L101-L103 the `config_path` function that's called is
```
<abscissa::command::entrypoint::EntryPoint<Cmd> as abscissa::config::configurable::Configurable<Cfg>>::config_path
```
(in fact the first `config_path` result is discarded, but the same function is called again inside of `load_config`).

But since the `EntryPoint` is created using `from_args`, there's no opportunity to actually set its config path, and the `config_path` function for the inner command is never called.

So I'm
a) not sure how to actually set the config path "correctly";
b) a little unclear on what the role of the `EntryPoint` struct is -- why not have `type Cmd = FooCommand`?.

**Comment by tarcieri** [comment]
`EntryPoint` not delegating to its `Cmd` is a definite bug, and unfortunately one not presently exercised by the existing boilerplate / tests.

Will fix ASAP.
