### ISSUE TITLE
Allow non-zero exit codes with `Application::shutdown()`

### ISSUE THREAD

**Issue by simonsan** [iqlusioninc/abscissa#857]
Currently, `shutdown` always returns `0` as exit code:

https://github.com/iqlusioninc/abscissa/blob/31bdcedea9dcee4777f3000a9a99751a57b987c1/core/src/application.rs#L160-L169

As a user of `abscissa` I would expect the following to return a non-zero exit code, when I pass `Shutdown::Crash`, though. 

```rust
 if let Err(err) = self.inner_run() {
            status_err!("{}", err);
            APP.shutdown(Shutdown::Crash);
        };
```

What's the opinion on changing that, to allow non-zero exit codes? We could directly return and call `process::exit()` ourselves, for sure. I'm unsure, though, whether it wouldn't be nice to stay within `abscissa` to let all the other components shutting down gracefully, while still exiting with a non-zero exit code. 

EDIT:

Maybe utilizing https://docs.rs/exitcode/1.1.2/exitcode/ these numbers?

```rust
 /// Shut down this application gracefully, exiting with your given `exit_code`. 
 fn shutdown_with_exit_code(&self, shutdown: Shutdown, exit_code: i32) -> ! { 
     let components = self.state().components(); 
  
     if let Err(e) = components.shutdown(self, shutdown) { 
         fatal_error(self, &e) 
     }; 
   
     process::exit(exit_code); 
 }
 ```

**Comment by aawsome** [comment]
Any news on this?

**Comment by simonsan** [comment]
@tony-iqlusion No stress, but it would be really awesome if there would be a new minor release (if applicable) for this, so we can use this in `rustic` and backups don't fail silently in scripts any more. The workaround would need to manually exit in a lot of places. :/

**Comment by tony-iqlusion** [comment]
There are some additional changes I'd like to make first, but I will try to get another release out soon

**Comment by simonsan** [comment]
> There are some additional changes I'd like to make first, but I will try to get another release out soon

Great, thank you! <3 Anything oneself can/you need help with?

**Comment by aawsome** [comment]
Don't want to put any pressure. Just wanted to mention that a release would help us to close an high-priority issue in https://github.com/rustic-rs/rustic
